### ISSUE TITLE
Publish new release for DMD's CI

### ISSUE THREAD

**Issue by JinShil** [DlangScience/scid#60]
scid is one of two projects causing a Jenkins CI failure for DMD (https://github.com/dlang/dmd/pull/8241) and preventing us from moving forward with a deprecation.   Looking through the code in scid's master branch, it appears the fix has already been made, but it needs to be tagged and released for DMD's CI to pick it up.

**Comment by John-Colvin** [comment]
@kyllingstad you ok with a new release? Just a point one.

Would be good if https://github.com/DlangScience/scid/pull/62 got in first

**Comment by JinShil** [comment]
This also seems to be preventing Jenkins from passing at https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6515/1/pipeline due to a no longer present dependency on the deprecated `std.c` package.

**Comment by wilzbach** [comment]
How about giving more people permissions so that such simple things as bumping a tag don't need to stall for weeks?

**Comment by John-Colvin** [comment]
I have permissions, I just wanted to give @kyllingstad a chance to comment. I've done a new release, let me know if there are any other problems

**Comment by kyllingstad** [comment]
Sorry for being slow to answer, but for the record, I'm totally ok with it. :-)
